name: Build and Publish image to Docker Hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up executable permissions for scripts
        run: chmod +x ./docker/build.sh ./docker/run.sh

      - name: Build Docker Image and Run the Docker container
        run: ./docker/build.sh

      - name: Retag image for Docker Hub
        run: docker tag docker-platform-app:latest ${{ secrets.DOCKER_HUB_USER }}/cms-platform-app:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/cms-platform-app:latest
