name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up executable permissions for scripts
      run: chmod +x ./docker/build.sh ./docker/run.sh
    - name: Build the Docker image
      run: ./docker/build.sh
    - name: Run the Docker container
      run: ./docker/run.sh
